# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c6b7cd9998e1c17b8b5c529723e147c6a3e9a572a2891c70d5ddccaae4a6ebcbfe0b8b44e4163633084f570b7c548f3eecb20021886bed370d24513352e6bae2

test:
  secret_key_base: 04ec35f8fc6f914420f38deed5ac1e245c79e6c21cacb3292471fa969ee74bdb69073ecc740b52edb1ae6e6c3439b8274936689ec99814f2a0745092ecbb2e1d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
